In [1]:
import pandas as pd
import numpy as np

In [2]:
property_data = pd.read_csv("D:/Desktop/supervised learning/datasets/property data.csv")

In [3]:
property_data.head()

PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
2  100003000.0     NaN  LEXINGTON            N          NaN        1   850
3  100004000.0   201.0   BERKELEY           12            1      NaN   700
4          NaN   203.0   BERKELEY            Y            3        2  1600

In [4]:
property_data.shape

(9, 7)

In [5]:
print("street number values \n\n", property_data['ST_NUM'])
print("\n Empty values in street number column \n\n", property_data['ST_NUM'].isnull())

street number values 

 0    104.0
1    197.0
2      NaN
3    201.0
4    203.0
5    207.0
6      NaN
7    213.0
8    215.0
Name: ST_NUM, dtype: float64

 Empty values in street number column 

 0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: ST_NUM, dtype: bool


In [6]:
missing_values = ['NaN', 'na', '--']
property_data = pd.read_csv("D:/Desktop/supervised learning/datasets/property data.csv", na_values = missing_values)

In [7]:
print("Number of bedroooms of property dataset \n\n", property_data['NUM_BEDROOMS'])
print("\n Null values in the column \n\n", property_data['NUM_BEDROOMS'].isnull())

Number of bedroooms of property dataset 

 0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    1.0
8    NaN
Name: NUM_BEDROOMS, dtype: float64

 Null values in the column 

 0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8     True
Name: NUM_BEDROOMS, dtype: bool


In [8]:
count = 0
for row in property_data['OWN_OCCUPIED']:
    try:
        int(row)
        property_data.loc[count, "OWN_OCCUPIED"] = np.nan
    except ValueError:
        pass
    count += 1

In [9]:
print("Missing values for each feature\n\n", property_data.isnull().sum())

Missing values for each feature

 PID             1
ST_NUM          2
ST_NAME         0
OWN_OCCUPIED    2
NUM_BEDROOMS    3
NUM_BATH        1
SQ_FT           2
dtype: int64


In [10]:
print("To check for any missing values: ", property_data.isnull().values.any())

To check for any missing values:  True


In [11]:
print("Total count of missing values: ", property_data.isnull().sum().sum())

Total count of missing values:  11


In [12]:
property_data['ST_NUM'].fillna(125, inplace = True)
property_data['ST_NUM']

0    104.0
1    197.0
2    125.0
3    201.0
4    203.0
5    207.0
6    125.0
7    213.0
8    215.0
Name: ST_NUM, dtype: float64

In [13]:
property_data.loc[2, 'ST_NUM'] = 126
property_data['ST_NUM']

0    104.0
1    197.0
2    126.0
3    201.0
4    203.0
5    207.0
6    125.0
7    213.0
8    215.0
Name: ST_NUM, dtype: float64

In [14]:
property_data['OWN_OCCUPIED'].fillna('missing', inplace=True)
property_data['OWN_OCCUPIED']

0          Y
1          N
2          N
3    missing
4          Y
5          Y
6    missing
7          Y
8          Y
Name: OWN_OCCUPIED, dtype: object

In [15]:
median = property_data['NUM_BEDROOMS'].median()
property_data['NUM_BEDROOMS'].fillna(median, inplace=True)

In [16]:
mean = property_data['NUM_BEDROOMS'].mean()
property_data['NUM_BEDROOMS'].fillna(mean, inplace=True)

In [17]:
mode = property_data['OWN_OCCUPIED'].mode()
property_data['OWN_OCCUPIED'].fillna(mode, inplace=True)

In [18]:
property_data['OWN_OCCUPIED'].fillna(method = 'backfill')

0          Y
1          N
2          N
3    missing
4          Y
5          Y
6    missing
7          Y
8          Y
Name: OWN_OCCUPIED, dtype: object

In [19]:
property_data['OWN_OCCUPIED'].fillna(method = 'ffill')

0          Y
1          N
2          N
3    missing
4          Y
5          Y
6    missing
7          Y
8          Y
Name: OWN_OCCUPIED, dtype: object

In [20]:
missing_info = list(property_data.columns[property_data.isnull().any()])
missing_info

['PID', 'NUM_BATH', 'SQ_FT']

In [21]:
for col in missing_info:
    num_missing = property_data[property_data[col].isnull()==True].shape[0]
    print("NUmber of misisng values in column {}: {}".format(col, num_missing))

NUmber of misisng values in column PID: 1
NUmber of misisng values in column NUM_BATH: 1
NUmber of misisng values in column SQ_FT: 2


In [22]:
for col in missing_info:
    percent_missing = float(property_data[property_data[col].isnull()==True].shape[0]/ property_data.shape[0])
    print("Percent missing from column {}: {}".format(col, percent_missing))

Percent missing from column PID: 0.1111111111111111
Percent missing from column NUM_BATH: 0.1111111111111111
Percent missing from column SQ_FT: 0.2222222222222222


In [23]:
property_data

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   126.0   LEXINGTON            N           2.5        1   850.0
3  100004000.0   201.0    BERKELEY      missing           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           2.5        1   800.0
6  100007000.0   125.0  WASHINGTON      missing           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           2.5        2  1800.0

In [24]:
property_data.dropna(axis=0, how='all')
property_data

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   126.0   LEXINGTON            N           2.5        1   850.0
3  100004000.0   201.0    BERKELEY      missing           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           2.5        1   800.0
6  100007000.0   125.0  WASHINGTON      missing           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           2.5        2  1800.0

In [25]:
property_data.dropna(axis=0, how='any')
property_data

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   126.0   LEXINGTON            N           2.5        1   850.0
3  100004000.0   201.0    BERKELEY      missing           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           2.5        1   800.0
6  100007000.0   125.0  WASHINGTON      missing           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           2.5        2  1800.0

In [26]:
dummy_ST_NAME = pd.get_dummies(property_data['ST_NAME'], prefix='State')
dummy_ST_NAME

State_BERKELEY  State_LEXINGTON  State_PUTNAM  State_TREMONT  \
0               0                0             1              0   
1               0                1             0              0   
2               0                1             0              0   
3               1                0             0              0   
4               1                0             0              0   
5               1                0             0              0   
6               0                0             0              0   
7               0                0             0              1   
8               0                0             0              1   

   State_WASHINGTON  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
5                 0  
6                 1  
7                 0  
8                 0

In [27]:
column_name= property_data.columns.values.tolist()
print(column_name)

['PID', 'ST_NUM', 'ST_NAME', 'OWN_OCCUPIED', 'NUM_BEDROOMS', 'NUM_BATH', 'SQ_FT']


In [28]:
column_name.remove('ST_NAME')

In [29]:
property_data[column_name].join(dummy_ST_NAME)

PID  ST_NUM OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT  \
0  100001000.0   104.0            Y           3.0        1  1000.0   
1  100002000.0   197.0            N           3.0      1.5     NaN   
2  100003000.0   126.0            N           2.5        1   850.0   
3  100004000.0   201.0      missing           1.0      NaN   700.0   
4          NaN   203.0            Y           3.0        2  1600.0   
5  100006000.0   207.0            Y           2.5        1   800.0   
6  100007000.0   125.0      missing           2.0   HURLEY   950.0   
7  100008000.0   213.0            Y           1.0        1     NaN   
8  100009000.0   215.0            Y           2.5        2  1800.0   

   State_BERKELEY  State_LEXINGTON  State_PUTNAM  State_TREMONT  \
0               0                0             1              0   
1               0                1             0              0   
2               0                1             0              0   
3               1                0             0              0   
4               1                0             0              0   
5               1                0             0              0   
6               0                0             0              0   
7               0                0             0              1   
8               0                0             0              1   

   State_WASHINGTON  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
5                 0  
6                 1  
7                 0  
8                 0

In [30]:
data = np.array([[1, 1, 2], [0, 2, 3], [1, 0, 1], [0, 1, 0]])
print(data)

[[1 1 2]
 [0 2 3]
 [1 0 1]
 [0 1 0]]


In [31]:
from sklearn import preprocessing
encoder = preprocessing.OneHotEncoder()
encoder.fit(data)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [32]:
encoder_vector = encoder.transform([[1,2,3]]).toarray()
encoder_vector

array([[0., 1., 0., 0., 1., 0., 0., 0., 1.]])

In [33]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
input_class = ['audi', 'ford', 'audi', 'toyota', 'ford', 'bmw']

In [35]:
label_encoder.fit(input_class)
print("Enoded class mapping:")
for i, item in enumerate(label_encoder.classes_):
    print(item, "-->",i)

Enoded class mapping:
audi --> 0
bmw --> 1
ford --> 2
toyota --> 3


In [36]:
labels = ['toyota','ford','audi']
encoded_labels = label_encoder.transform(labels)
print("labels: ",labels)
print("encoded labels: ", encoded_labels)

labels:  ['toyota', 'ford', 'audi']
encoded labels:  [3 2 0]


In [37]:
encoded_labels=[2, 1, 0, 3, 1]
decoded_labels = label_encoder.inverse_transform(encoded_labels)
print("encoded labels: ", encoded_labels)
print("decoded labels: ", decoded_labels)

encoded labels:  [2, 1, 0, 3, 1]
decoded labels:  ['ford' 'bmw' 'audi' 'toyota' 'bmw']


C:\Users\bhave\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
